import { execa } from "execa"
import fse from "fs-extra"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { commandExists, error, header, info, loading, success, warn } from "../../utils/exec.js"


async function cleanOpenspecFiles() {
  const cwd = process.cwd()
  const commandsDir = path.join(cwd, '.opencode', 'commands')
  const opencodeSkillsDir = path.join(cwd, '.opencode', 'skills')
  const agentsSkillsDir = path.join(cwd, '.agents', 'skills')

  // Delete opsx-* command files generated by OpenSpec — we use /ob-propose and /ob-apply instead
  if (await fse.pathExists(commandsDir)) {
    for (const f of await fse.readdir(commandsDir)) {
      if (f.startsWith('opsx-') && f.endsWith('.md')) {
        await fse.remove(path.join(commandsDir, f))
        info(`Removed generated command: ${f}`)
      }
    }
  }

  // Move .opencode/skills/* to .agents/skills/ — skills should be in the universal location
  if (await fse.pathExists(opencodeSkillsDir)) {
    await fse.ensureDir(agentsSkillsDir)
    for (const dir of await fse.readdir(opencodeSkillsDir)) {
      const src = path.join(opencodeSkillsDir, dir)
      const dest = path.join(agentsSkillsDir, dir)
      if (!(await fse.pathExists(dest))) {
        await fse.move(src, dest)
        info(`Moved skill: ${dir} → .agents/skills/`)
      } else {
        await fse.remove(src)
      }
    }
    // Remove .opencode/skills if now empty
    const remaining = await fse.readdir(opencodeSkillsDir)
    if (remaining.length === 0) await fse.remove(opencodeSkillsDir)
  }

  success('OpenSpec generated files cleaned up')
}

export const openspecSteps = {
  check,
  install,
  init,
}

export async function initOpenspec() {
  header("Step 6, Initializing OpenSpec")

  let openSpec = await openspecSteps.check()
  if (!openSpec.available) {
    await openspecSteps.install()
  }

  openSpec = await openspecSteps.check()
  if (!openSpec.available) {
    warn("OpenSpec has not been installed. It is required to create changes.")
    return { ...openSpec, initialized: false }
  }

  const initResult = await openspecSteps.init()
  if (!initResult.initialized) {
    warn(
      "OpenSpec has not been initialized. It is required to create changes.",
    )
    return { ...openSpec, initialized: false }
  }

  await cleanOpenspecFiles()
  return { ...openSpec, initialized: true }
}

async function install() {
  info("Installing OpenSpec...")
  try {
    const result = await execa(
      "npm",
      ["install", "@fission-ai/openspec", "--global"],
      {
        cwd: process.cwd(),
        stdio: "pipe",
        reject: false,
      },
    )
    if (result.exitCode !== 0) {
      warn("OpenSpec install failed, check output above")
    }
    success("OpenSpec installed")
  } catch (err) {
    error(`Failed to run openspec install: ${err.message}`)
  }
}

async function check() {
  loading("Checking OpenSpec...")

  const available = await commandExists("openspec")

  if (available) success("OpenSpec is available")
  else warn("OpenSpec not found on PATH.")

  return { available }
}

async function init() {
  loading("Initializing OpenSpec...")
  try {
    const result = await execa(
      "npx",
      ["@fission-ai/openspec", "init", "--tools", "opencode", "--force"],
      {
        cwd: process.cwd(),
        reject: false,
      },
    )

    if (result.exitCode !== 0) {
      const stderr = (result.stderr || "").trim()
      const msg = stderr
        ? `init failed: ${stderr}`
        : `init failed with exit code ${result.exitCode}`
      throw new Error(msg)
    }
  } catch (err) {
    error(`Failed to run openspec init: ${err.message}`)
    return { initialized: false }
  }

  success("OpenSpec initialized")
  return { initialized: true }
}


